CREATE TABLE PRICE(
PRICE_CODE      INT     NOT NULL    UNIQUE,
PRICE_DESCRIPTION       VARCHAR(50)     NOT NULL,
PRICE_RENTFEE           NUMERIC(4,2)    NOT NULL,
PRICE_DAILYLATEFEE      NUMERIC(4,2)    NOT NULL,
CONSTRAINT PRICE_PRICE_CODE_PK PRIMARY KEY (PRICE_CODE),
);