CREATE TABLE VIDEO (
VID_NUM      INT     NOT NULL    UNIQUE,
VID_INDATE   DATE    NOT NULL,
MOVIE_NUM    INT     NOT NULL,
CONSTRAINT VIDEO_VID_NUM_PK PRIMARY KEY (VID_NUM),
CONSTRAINT VIDEO_MOVIE_NUM_FK FOREIGN KEY  (MOVIE_NUM) REFERENCES MOVIE (MOVIE_NUM)
 );