CREATE TABLE RENTAL (
RENT_NUM      INT         NOT NULL    UNIQUE,
RENT_DATE     DATE        NOT NULL,
MEM_NUM       INT         NOT NULL,
CONSTRAINT RENTAL_RENT_NUM_PK PRIMARY KEY (RENT_NUM),
CONSTRAINT RENTAL_MEM_NUM_FK FOREIGN KEY  (MEM_NUM) REFERENCES MEMBERSHIP (MEM_NUM)
 );