/* Join Statements */
-- 2
SELECT PROJ_NAME, PROJ_VALUE, PROJ_BALANCE, EMP_LNAME, EMP_FNAME, EMP_INITIAL, JOB.JOB_CODE, JOB_DESCRIPTION, JOB_CHG_HOUR
FROM PROJECT JOIN EMPLOYEE ON PROJECT.EMP_NUM = EMPLOYEE.EMP_NUM JOIN JOB ON EMPLOYEE.JOB_CODE = JOB.JOB_CODE
ORDER BY PROJ_VALUE;

-- 3
SELECT PROJ_NAME, PROJ_VALUE, PROJ_BALANCE, EMP_LNAME, EMP_FNAME, EMP_INITIAL, JOB.JOB_CODE, JOB_DESCRIPTION, JOB_CHG_HOUR
FROM PROJECT JOIN EMPLOYEE ON PROJECT.EMP_NUM = EMPLOYEE.EMP_NUM JOIN JOB ON EMPLOYEE.JOB_CODE = JOB.JOB_CODE
ORDER BY EMP_LNAME;

-- 6
SELECT ASSIGNMENT.EMP_NUM, EMP_LNAME, Sum(ASSIGN_HOURS) AS SumOfASSIGN_HOURS, Sum(ASSIGN_CHARGE) AS SumOfASSIGN_CHARGE
FROM EMPLOYEE JOIN ASSIGNMENT ON EMPLOYEE.EMP_NUM = ASSIGNMENT.EMP_NUM
GROUP BY ASSIGNMENT.EMP_NUM, EMPLOYEE.EMP_LNAME
ORDER BY ASSIGNMENT.EMP_NUM;


-- 11
SELECT CUS_CODE, INVOICE.INV_NUMBER, INV_DATE, P_DESCRIPT, LINE_UNITS, LINE_PRICE
FROM INVOICE JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER JOIN PRODUCT ON PRODUCT.P_CODE = LINE.P_CODE
ORDER BY CUS_CODE, INVOICE.INV_NUMBER, P_DESCRIPT;


-- 12
SELECT CUS_CODE, INVOICE.INV_NUMBER, P_DESCRIPT, LINE_UNITS AS "Units Bought", LINE_PRICE AS "Unit Price", LINE_UNITS * LINE_PRICE AS Subtotal
FROM INVOICE JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER JOIN PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE
ORDER BY CUS_CODE, INVOICE.INV_NUMBER, P_DESCRIPT;

-- 13
SELECT 	CUSTOMER.CUS_CODE, CUS_BALANCE, SUM(LINE_UNITS * LINE_PRICE) AS "Total Purchases"
FROM CUSTOMER JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
GROUP BY CUSTOMER.CUS_CODE, CUS_BALANCE
ORDER BY CUSTOMER.CUS_CODE;

-- 14
SELECT 	CUSTOMER.CUS_CODE, CUS_BALANCE, SUM(LINE_UNITS * LINE_PRICE) AS "Total Purchases", COUNT(*) AS "Number of Purchases"
FROM CUSTOMER JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
GROUP BY CUSTOMER.CUS_CODE, CUS_BALANCE
ORDER BY CUSTOMER.CUS_CODE;

-- 15
SELECT CUSTOMER.CUS_CODE, CUS_BALANCE, SUM(LINE_UNITS * LINE_PRICE) AS "Total Purchases", COUNT(*) AS "Number of Purchases", AVG(LINE_UNITS * LINE_PRICE) AS "Average Purchase Amount"
FROM CUSTOMER JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
GROUP BY CUSTOMER.CUS_CODE, CUS_BALANCE
ORDER BY CUSTOMER.CUS_CODE;












